server:
  port: 8888
  tomcat:
      uri-encoding: utf-8
  # HTTP请求和响应头的最大量，以字节为单位，默认值为4096字节,超过此长度的部分不予处理,一般8K。解决java.io.EOFException: null问题
  max-http-header-size: 8192
  use-forward-headers: true
  compression:
      enabled: true
      min-response-size: 1024
      mime-types: text/plain,text/css,text/xml,text/javascript,application/json,application/javascript,application/xml,application/xml+rss,application/x-javascript,application/x-httpd-php,image/jpeg,image/gif,image/png
spring:
  thymeleaf:
    # 配置thymeleaf修改页面不重启生效
    prefix: file:src/main/resources/templates/
    cache: false
  datasource:
      driverClassName: com.mysql.jdbc.Driver
      url: jdbc:mysql://localhost:3306/zb-shiro?useUnicode=true&characterEncoding=UTF-8&useSSL=false
      username: root
      password: 123456
      type: com.alibaba.druid.pool.DruidDataSource
      initial-size: 1
      minIdle: 3
      maxActive: 20
      maxWait: 60000
      filters: stat,wall,slf4j
  application:
      name: hope-admin
  freemarker:
      allow-request-override: false
      allow-session-override: false
      cache: false
      charset: UTF-8
      check-template-location: true
      content-type: text/html
      enabled: true
      expose-request-attributes: false
      expose-session-attributes: false
      expose-spring-macro-helpers: true
      prefer-file-system-access: true
      suffix: .ftl
      template-loader-path: classpath:/templates/
      settings:
          template_update_delay: 0
          default_encoding: UTF-8
          classic_compatible: true
  # HTTP ENCODING
  http:
      multipart:
          #max-file-size: 2MB
          #max-request-size: 10MB
      encoding:
          enabled: true
          charset: UTF-8
          force: true
  messages:
      encoding: UTF-8
  jmx:
      enabled: true
      default-domain: agentservice
  resources:
      chain:
          strategy:
              content:
                  enabled: true
                  paths: /**
mybatis:
    type-aliases-package: com.ad.core.hope.model
    mapper-locations: classpath:/mapper/*.xml
mapper:
    mappers:
        - com.ad.core.hope.util.MyMapper
    not-empty: false
    identity: MYSQL
pagehelper:
    helper-dialect: mysql
    reasonable: true
    support-methods-arguments: true
    params: count=countSql
logging:
    file: ./logs/log.log
################################### 程序自定义配置 ###################################
hope:
    druid:
        # druid访问用户名（默认：zyd-druid）
        username: hope-druid
        # druid访问密码（默认：zyd-druid）
        password: hope-druid
        # druid访问地址（默认：/druid/*）
        servletPath: /druid/*
        # 启用重置功能（默认false）
        resetEnable: false
        # 白名单(非必填)， list
        allowIps[0]:
        # 黑名单(非必填)， list
        denyIps[0]: